apiVersion: v1
kind: Pod
metadata:
  name: kubewatch
  namespace : monitor
spec:
  containers:
  - image: jungchangun/kubewatch:latest
  # bitnami/kubewatch:latest
    env : 
    - name : KW_WEBHOOK_URL
      value : ""
    resources:
      requests:
        memory: "10Mi"
        cpu: "05m"
      limits:
        memory: "20Mi"
        cpu: "10m"
    imagePullPolicy: Always
    name: kubewatch
    volumeMounts:
    - name: config-volume
      mountPath: /.kubewatch.yaml
      subPath: .kubewatch.yaml
  - image: bitnami/kubectl:latest
    resources:
      requests:
        memory: "10Mi"
        cpu: "05m"
      limits:
        memory: "15Mi"
        cpu: "10m"
    args:
      - proxy
      - "-p"
      - "8080"
    name: proxy
    imagePullPolicy: Always
  restartPolicy: Always
  serviceAccount: kubewatch
  serviceAccountName: kubewatch
  volumes:
  - name: config-volume
    configMap:
      name: kubewatch
